name: Sync from upstream

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch: # allow manual run too

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Git
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"

      - name: Add upstream
        run: |
          git remote add upstream https://github.com/EQEmu/eqemu-docs-v2
          git fetch upstream

      - name: Merge upstream main
        run: |
          git checkout main
          git merge --no-edit upstream/main || echo "No changes to merge"
          git push origin main

